name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:    
    - uses: actions/checkout@v2
    - name: step-1
      run: echo $JOBENV
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./Signals/src/Signals.sln 
    - name: Build
      run: dotnet build ../../Signals/src/Signals.sln   --no-restore
    - name: Test
      run: dotnet test ../../Signals/src/Signals.Test/Signals.Tests.csproj --no-build --verbosity normal
